name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    # - uses: jakejarvis/s3-sync-action@master
    - name: Uploading to ec2 deployment server
      run: rsync -zhrv ./* ubuntu@13.233.103.3:/home/ubuntu/test
      
    - name: Uploading to s3 Deployment server
      run: aws s3 cp index.html s3://github-demo-s3
